sets.exported={
    head={ name="Adhemar Bonnet", augments={'DEX+10','AGI+10','Accuracy+15',}},
    head={ name="Herculean Helm", augments={'Rng.Acc.+28','"Subtle Blow"+1','DEX+1','Rng.Atk.+15',}},
    head={ name="Herculean Helm", augments={'Mag. Acc.+19 "Mag.Atk.Bns."+19','Crit. hit damage +2%','STR+9','"Mag.Atk.Bns."+12',}},
    body={ name="Adhemar Jacket", augments={'DEX+10','AGI+10','Accuracy+15',}},
    body={ name="Herculean Vest", augments={'Accuracy+28','Crit.hit rate+5','DEX+5','Attack+12',}},
    body="Sayadio's Kaftan",
    item="Beitetsu",
    hands={ name="Herculean Gloves", augments={'Accuracy+16','Crit.hit rate+5','DEX+1',}},
    hands={ name="Herculean Gloves", augments={'Accuracy+29','"Triple Atk."+3','STR+9',}},
    legs={ name="Herculean Trousers", augments={'Accuracy+14 Attack+14','DEX+9','Accuracy+15','Attack+14',}},
    legs={ name="Herculean Trousers", augments={'Rng.Acc.+23 Rng.Atk.+23','Enmity-1','AGI+7','Rng.Atk.+15',}},
    item="Savory Shank",
    legs={ name="Herculean Trousers", augments={'Attack+27','"Triple Atk."+4','AGI+4','Accuracy+15',}},
    feet={ name="Herculean Boots", augments={'AGI+10','"Store TP"+2','Magic Damage +17','Mag. Acc.+20 "Mag.Atk.Bns."+20',}},
    feet={ name="Herculean Boots", augments={'Rng.Acc.+20 Rng.Atk.+20','Crit.hit rate+2','Rng.Acc.+12','Rng.Atk.+9',}},
    feet={ name="Herculean Boots", augments={'Accuracy+14 Attack+14','"Triple Atk."+4','VIT+6','Accuracy+5',}},
    waist="Windbuffet Belt +1",
    back={ name="Andartia's Mantle", augments={'AGI+12',}},
    item="Silt Pouch",
    head={ name="Ryuo Somen", augments={'STR+10','DEX+10','Accuracy+15',}},
    back={ name="Mecisto. Mantle", augments={'Cap. Point+50%','VIT+1','Rng.Acc.+3','DEF+6',}},
    back={ name="Yokaze Mantle", augments={'STR+2','DEX+3','Sklchn.dmg.+4%',}},
    ammo="Happo Shuriken",
    head={ name="Lilitu Headpiece", augments={'STR+10','DEX+10','Attack+15','Weapon skill damage +3%',}},
    head={ name="Rao Kabuto", augments={'STR+10','DEX+10','Attack+15',}},
    head={ name="Pursuer's Beret", augments={'AGI+10','"Rapid Shot"+10','"Subtle Blow"+7',}},
    body={ name="Pursuer's Doublet", augments={'HP+50','Crit. hit rate+4%','"Snapshot"+6',}},
    body={ name="Samnuha Coat", augments={'Mag. Acc.+8','"Mag.Atk.Bns."+11','"Dual Wield"+2',}},
    hands="Rao Kote",
    hands={ name="Pursuer's Cuffs", augments={'AGI+10','"Rapid Shot"+10','"Subtle Blow"+7',}},
    hands={ name="Ryuo Tekko", augments={'DEX+10','Accuracy+20','"Dbl.Atk."+3',}},
    hands={ name="Floral Gauntlets", augments={'Rng.Acc.+15','Accuracy+15','"Triple Atk."+3','Magic dmg. taken -4%',}},
    legs={ name="Rao Haidate", augments={'STR+10','DEX+10','Attack+15',}},
    legs={ name="Pursuer's Pants", augments={'AGI+10','"Rapid Shot"+10','"Subtle Blow"+7',}},
    legs={ name="Ryuo Hakama", augments={'STR+10','DEX+10','Accuracy+15',}},
    feet="Rao Sune-Ate",
    feet={ name="Pursuer's Gaiters", augments={'Rng.Acc.+10','"Rapid Shot"+10','"Recycle"+15',}},
    body="Genie Weskit",
    feet={ name="Ryuo Sune-Ate", augments={'STR+10','DEX+10','Accuracy+15',}},
    head={ name="Valorous Mask", augments={'Accuracy+28','Weapon skill damage +3%','STR+15','Attack+12',}},
    head={ name="Valorous Mask", augments={'Accuracy+24 Attack+24','Crit.hit rate+3','STR+1','Accuracy+9','Attack+6',}},
    legs={ name="Valor. Hose", augments={'Accuracy+23 Attack+23','Weapon skill damage +1%','Accuracy+5','Attack+5',}},
    back={ name="Smertrios's Mantle", augments={'STR+20','Accuracy+16 Attack+16',}},
    back={ name="Takaha Mantle", augments={'STR+4','"Zanshin"+3','"Store TP"+2','Meditate eff. dur. +5',}},
    item="Gil",
}