https://onedrive.live.com/?authkey=%21AKFeq76Tdl7LbNM&id=18521B913EC1C4A9%21131398&cid=18521B913EC1C4A9
    main="Dojikiri Yasutsuna",
    sub="Bloodrain Strap",
    sub="Gracile Grip",
    head="Hizamaru Somen +1",
    head="Gavialis Helm",
    head="Stinger Helm +1",
    head="Wakido Kabuto +1",
    body="Hiza. Haramaki +1",
    body="Kasuga Domaru +1",
    hands="Hizamaru Kote +1",
    hands={ name="Sakonji Kote +1", augments={'Enhances "Blade Bash" effect',}},
    hands="Wakido Kote +1",
    legs="Arjuna Breeches",
    legs="Hiza. Hizayoroi +1",
    legs={ name="Sakonji Haidate +1", augments={'Enhances "Shikikoyo" effect',}},
    legs="Kasuga Haidate +1",
    legs="Wakido Haidate +1",
    feet="Hiza. Sune-Ate +1",
    feet={ name="Sak. Sune-Ate +1", augments={'Enhances "Meikyo Shisui" effect',}},
    feet="Waki. Sune-Ate +1",
    neck="Ainia Collar",
    waist="Kentarch Belt +1",
    left_ear="Dedition Earring",
    left_ear="Tripudio Earring",
    left_ring="Cacoethic Ring",
    left_ring="Cacoethic Ring +1",
    left_ring="Ifrit Ring",
    left_ring="Ifrit Ring",
    left_ring="Rajas Ring",
    range={ name="Cibitshavore", augments={'STR+12','Rng.Acc.+10','"Store TP"+7',}},
    head={ name="Ryuo Somen", augments={'STR+10','DEX+10','Accuracy+15',}},
    head={ name="Valorous Mask", augments={'Accuracy+30','"Dbl.Atk."+2','STR+2','Attack+12',}},
    head={ name="Valorous Mask", augments={'Accuracy+28','Weapon skill damage +3%','STR+15','Attack+12',}},
    head={ name="Rao Kabuto", augments={'STR+10','DEX+10','Attack+15',}},
    head={ name="Founder's Corona", augments={'DEX+10','Accuracy+15','Mag. Acc.+15','Magic dmg. taken -5%',}},
    body={ name="Found. Breastplate", augments={'Accuracy+14','Mag. Acc.+13','Attack+14','"Mag.Atk.Bns."+14',}},
    hands={ name="Rao Kote", augments={'Accuracy+7','Attack+7','Evasion+9',}},
    body="Genie Weskit",
    hands={ name="Ryuo Tekko", augments={'DEX+10','Accuracy+20','"Dbl.Atk."+3',}},
    hands={ name="Valorous Mitts", augments={'Accuracy+26','"Store TP"+6','Attack+5',}},
    hands={ name="Founder's Gauntlets", augments={'STR+10','Attack+15','"Mag.Atk.Bns."+15','Phys. dmg. taken -5%',}},
    legs={ name="Valor. Hose", augments={'Accuracy+22','"Store TP"+7','STR+15','Attack+11',}},
    legs={ name="Rao Haidate", augments={'STR+10','DEX+10','Attack+15',}},
    legs={ name="Ryuo Hakama", augments={'STR+10','DEX+10','Accuracy+15',}},
    legs={ name="Founder's Hose", augments={'MND+9','Mag. Acc.+13','Attack+14','Breath dmg. taken -4%',}},
    feet="Rao Sune-Ate",
    feet={ name="Ryuo Sune-Ate", augments={'STR+10','DEX+10','Accuracy+15',}},
    feet={ name="Valorous Greaves", augments={'Accuracy+24','"Store TP"+5','Attack+4',}},
    feet={ name="Founder's Greaves", augments={'VIT+10','Accuracy+15','"Mag.Atk.Bns."+15','Mag. Evasion+15',}},
    back={ name="Smertrios's Mantle", augments={'STR+20','Accuracy+20 Attack+20','Weapon skill damage +10%',}},
    back={ name="Takaha Mantle", augments={'STR+4','"Zanshin"+3','"Store TP"+2','Meditate eff. dur. +5',}},
    left_ring="Lebeche Ring",
    back={ name="Mecisto. Mantle", augments={'Cap. Point+50%','VIT+1','Rng.Acc.+3','DEF+6',}},
    left_ring="Paguroidea Ring",
    left_ring="K'ayres Ring",
    waist="Dynamic Belt +1",
    left_ear="Zwazo Earring +1",
    body="Uac Jerkin",
    left_ear="Odnowa Earring",
    body="Vatic Byrnie",
    item="Gil",
}
