 sub={ name="Skinflayer", augments={'"Triple Atk."+3','Accuracy+10','Attack+13','DMG:+17',}},
    sub={ name="Skinflayer", augments={'"Triple Atk."+2','CHR+1','Accuracy+19','Attack+19','DMG:+18',}},
    sub={ name="Colada", augments={'"Refresh"+2','INT+1','Mag. Acc.+15','"Mag.Atk.Bns."+10',}},
    sub={ name="Colada", augments={'"Store TP"+4','DEX+14','Accuracy+10','DMG:+16',}},
    main={ name="Zulfiqar", augments={'Weapon Skill Acc.+5','STR+6','Attack+14','DMG:+24',}},
    sub="Heishi Shorinken",
    sub={ name="Kanaria", augments={'Weapon skill damage +3%','DEX+2','Accuracy+13','DMG:+11',}},
    main={ name="Grioavolr", augments={'"Fast Cast"+7','MP+54','Mag. Acc.+29','"Mag.Atk.Bns."+28','Magic Damage +3',}},
    ammo="Impatiens",
    head={ name="Odyssean Helm", augments={'Attack+9','Weapon skill damage +4%','STR+3','Accuracy+13',}},
    head={ name="Odyssean Helm", augments={'Accuracy+28','"Dbl.Atk."+3','CHR+4','"Mag.Atk.Bns."+3',}},
    head={ name="Valorous Mask", augments={'Pet: Accuracy+30 Pet: Rng. Acc.+30','"Store TP"+1','Pet: DEX+10','Pet: Attack+14 Pet: Rng.Atk.+14',}},
    head={ name="Valorous Mask", augments={'Accuracy+30','"Dbl.Atk."+2','STR+2','Attack+12',}},
    head={ name="Valorous Mask", augments={'Accuracy+28','Weapon skill damage +3%','STR+15','Attack+12',}},
    head={ name="Herculean Helm", augments={'Rng.Acc.+25 Rng.Atk.+25','Enmity-7','Rng.Atk.+15',}},
    head={ name="Herculean Helm", augments={'Mag. Acc.+19 "Mag.Atk.Bns."+19','Magic burst mdg.+4%','STR+3','Mag. Acc.+10','"Mag.Atk.Bns."+11',}},
    head={ name="Merlinic Hood", augments={'Mag. Acc.+17 "Mag.Atk.Bns."+17','"Fast Cast"+6','INT+6','Mag. Acc.+10','"Mag.Atk.Bns."+14',}},
    head={ name="Merlinic Hood", augments={'Mag. Acc.+23 "Mag.Atk.Bns."+23','Magic burst mdg.+4%','Mag. Acc.+13','"Mag.Atk.Bns."+9',}},
    head={ name="Chironic Hat", augments={'Mag. Acc.+25 "Mag.Atk.Bns."+25','"Conserve MP"+1','VIT+1','Mag. Acc.+8',}},
    body={ name="Valorous Mail", augments={'Pet: Accuracy+30 Pet: Rng. Acc.+30','Pet: "Store TP"+3','Pet: DEX+14',}},
    body={ name="Valorous Mail", augments={'Accuracy+17 Attack+17','Weapon skill damage +5%','STR+8','Accuracy+14','Attack+5',}},
    body={ name="Herculean Vest", augments={'Accuracy+28','Crit.hit rate+5','DEX+5','Attack+12',}},
    body={ name="Merlinic Jubbah", augments={'Mag. Acc.+24 "Mag.Atk.Bns."+24','Magic burst mdg.+10%','CHR+7',}},
    body={ name="Chironic Doublet", augments={'Mag. Acc.+29','Enmity-4','MND+2','"Mag.Atk.Bns."+6',}},
    body={ name="Chironic Doublet", augments={'Mag. Acc.+12','"Cure" potency +11%',}},
    body={ name="Acro Surcoat", augments={'Pet: Accuracy+10 Pet: Rng. Acc.+10','Pet: "Regen"+3','Pet: Damage taken -4%',}},
    hands={ name="Acro Gauntlets", augments={'Pet: Accuracy+17 Pet: Rng. Acc.+17','Pet: "Regen"+3','Pet: Damage taken -4%',}},
    hands={ name="Odyssean Gauntlets", augments={'Accuracy+22','DEX+9','Attack+3',}},
    hands={ name="Odyssean Gauntlets", augments={'Accuracy+23','Weapon skill damage +4%',}},
    hands={ name="Valorous Mitts", augments={'Accuracy+25 Attack+25','"Store TP"+3','Accuracy+14',}},
    hands={ name="Valorous Mitts", augments={'Accuracy+15 Attack+15','"Store TP"+8','CHR+8','Accuracy+5','Attack+10',}},
    hands={ name="Valorous Mitts", augments={'Pet: Accuracy+28 Pet: Rng. Acc.+28','Pet: "Regen"+1','Pet: DEX+4','Pet: Attack+11 Pet: Rng.Atk.+11',}},
    hands={ name="Valorous Mitts", augments={'Accuracy+18 Attack+18','Weapon Skill Acc.+10','STR+15','Accuracy+7','Attack+10',}},
    hands={ name="Herculean Gloves", augments={'Rng.Acc.+18 Rng.Atk.+18','Enmity-3','AGI+6','Rng.Acc.+9','Rng.Atk.+1',}},
    hands={ name="Herculean Gloves", augments={'Accuracy+29','"Triple Atk."+3','STR+9',}},
    hands={ name="Herculean Gloves", augments={'Accuracy+16','Crit.hit rate+5','DEX+1',}},
    hands={ name="Merlinic Dastanas", augments={'Mag. Acc.+21 "Mag.Atk.Bns."+21','INT+8','Mag. Acc.+3','"Mag.Atk.Bns."+15',}},
    hands={ name="Merlinic Dastanas", augments={'"Mag.Atk.Bns."+10','Pet: DEX+6','Phalanx +1','Accuracy+13 Attack+13','Mag. Acc.+18 "Mag.Atk.Bns."+18',}},
    hands={ name="Chironic Gloves", augments={'Mag. Acc.+24 "Mag.Atk.Bns."+24','MND+6','Mag. Acc.+10','"Mag.Atk.Bns."+14',}},
    legs={ name="Odyssean Cuisses", augments={'Accuracy+21','STR+14',}},
    legs={ name="Valor. Hose", augments={'Pet: Accuracy+30 Pet: Rng. Acc.+30','Pet: Haste+2','Pet: INT+10','Pet: Attack+14 Pet: Rng.Atk.+14',}},
    legs={ name="Valor. Hose", augments={'Accuracy+24 Attack+24','"Store TP"+5','VIT+8','Accuracy+3',}},
    legs={ name="Herculean Trousers", augments={'Pet: Phys. dmg. taken -1%','"Fast Cast"+3','"Treasure Hunter"+1','Accuracy+11 Attack+11','Mag. Acc.+1 "Mag.Atk.Bns."+1',}},
    legs={ name="Herculean Trousers", augments={'Mag. Acc.+15 "Mag.Atk.Bns."+15','Enmity-5','AGI+3','Mag. Acc.+12','"Mag.Atk.Bns."+11',}},
    legs={ name="Herculean Trousers", augments={'Attack+27','"Triple Atk."+4','AGI+4','Accuracy+15',}},
    legs={ name="Herculean Trousers", augments={'Rng.Acc.+23 Rng.Atk.+23','Enmity-1','AGI+7','Rng.Atk.+15',}},
    legs={ name="Merlinic Shalwar", augments={'"Mag.Atk.Bns."+21','Magic burst mdg.+9%','INT+1','Mag. Acc.+13',}},
    legs={ name="Merlinic Shalwar", augments={'Mag. Acc.+24 "Mag.Atk.Bns."+24','"Occult Acumen"+9','CHR+5','"Mag.Atk.Bns."+13',}},
    legs={ name="Chironic Hose", augments={'Mag. Acc.+24 "Mag.Atk.Bns."+24','"Cure" spellcasting time -8%','Mag. Acc.+14',}},
    legs={ name="Taeon Tights", augments={'Pet: Accuracy+5 Pet: Rng. Acc.+5','Pet: "Regen"+3','Pet: Damage taken -4%',}},
    feet={ name="Acro Leggings", augments={'Pet: Attack+19 Pet: Rng.Atk.+19','Pet: "Regen"+3','Pet: Damage taken -4%',}},
    feet={ name="Odyssean Greaves", augments={'"Fast Cast"+3','VIT+5','Accuracy+9','Attack+15',}},
    feet={ name="Odyssean Greaves", augments={'Mag. Acc.+14 "Mag.Atk.Bns."+14','"Store TP"+5','MND+1','"Mag.Atk.Bns."+15',}},
    feet={ name="Odyssean Greaves", augments={'Accuracy+23','"Dbl.Atk."+2','STR+3',}},
    feet={ name="Valorous Greaves", augments={'Accuracy+24 Attack+24','Damage taken-1%','Accuracy+14',}},
    feet={ name="Valorous Greaves", augments={'Pet: Accuracy+28 Pet: Rng. Acc.+28','Pet: "Dbl. Atk."+1','Pet: DEX+9','Pet: Attack+5 Pet: Rng.Atk.+5',}},
    feet={ name="Valorous Greaves", augments={'Accuracy+27','"Store TP"+5','DEX+9','Attack+10',}},
    feet={ name="Herculean Boots", augments={'Accuracy+14 Attack+14','"Triple Atk."+4','VIT+6','Accuracy+5',}},
    feet={ name="Herculean Boots", augments={'AGI+10','"Store TP"+2','Magic Damage +17','Mag. Acc.+20 "Mag.Atk.Bns."+20',}},
    feet={ name="Herculean Boots", augments={'Rng.Acc.+20 Rng.Atk.+20','Crit.hit rate+2','Rng.Acc.+12','Rng.Atk.+9',}},
    feet={ name="Merlinic Crackows", augments={'Mag. Acc.+24 "Mag.Atk.Bns."+24','Magic burst mdg.+7%','CHR+2','Mag. Acc.+6','"Mag.Atk.Bns."+14',}},
    feet={ name="Merlinic Crackows", augments={'INT+1','Phys. dmg. taken -4%','"Refresh"+1','Accuracy+8 Attack+8',}},
    feet={ name="Chironic Slippers", augments={'Mag. Acc.+23 "Mag.Atk.Bns."+23','Haste+4','Mag. Acc.+13',}},
    waist="Witful Belt",
    left_ear="Etiolation Earring",
    left_ear="Dudgeon Earring",
    left_ear="Heartseeker Earring",
    left_ear={ name="Moonshade Earring", augments={'Accuracy+4','TP Bonus +25',}},
    left_ear="Loquac. Earring",
    left_ear="Brutal Earring",
    left_ring="Cacoethic Ring",
    left_ring="Cacoethic Ring +1",
    left_ring="Petrov Ring",
    left_ring="Vertigo Ring",
    left_ring="Rahab Ring",
    left_ring="Etana Ring",
    left_ring="Apate Ring",
    left_ring="Resonance Ring",
    left_ring="Warden's Ring",
    left_ring="Shiva Ring",
    
     sub={ name="Skullrender", augments={'DMG:+15','Pet: Accuracy+20','Pet: Attack+20',}},
    sub={ name="Skullrender", augments={'DMG:+15','Pet: Accuracy+20','Pet: Attack+20',}},
    sub={ name="Nibiru Tabar", augments={'Pet: Attack+25','Pet: "Mag.Atk.Bns."+15','Pet: Enmity+7',}},
    sub={ name="Nibiru Tabar", augments={'Pet: Attack+25','Pet: "Mag.Atk.Bns."+15','Pet: Enmity+7',}},
    sub={ name="Nibiru Cudgel", augments={'MP+50','INT+10','"Mag.Atk.Bns."+15',}},
    head={ name="Emicho Coronet", augments={'Pet: Accuracy+15','Pet: Attack+15','Pet: "Dbl. Atk."+3',}},
    head={ name="Ryuo Somen", augments={'STR+10','DEX+10','Accuracy+15',}},
    head={ name="Adhemar Bonnet", augments={'STR+10','DEX+10','Attack+15',}},
    head={ name="Amalric Coif", augments={'INT+10','Mag. Acc.+20','Enmity-5',}},
    head={ name="Lustratio Cap", augments={'Accuracy+15','DEX+5','Crit. hit rate+2%',}},
    head={ name="Argosy Celata", augments={'DEX+10','Accuracy+15','"Dbl.Atk."+2',}},
    head={ name="Rao Kabuto", augments={'STR+10','DEX+10','Attack+15',}},
    head={ name="Carmine Mask", augments={'Accuracy+15','Mag. Acc.+10','"Fast Cast"+3',}},
    head={ name="Despair Helm", augments={'Accuracy+10','Pet: VIT+7','Pet: Damage taken -3%',}},
    head={ name="Rawhide Mask", augments={'HP+50','Accuracy+15','Evasion+20',}},
    head={ name="Pursuer's Beret", augments={'AGI+10','"Rapid Shot"+10','"Subtle Blow"+7',}},
    head={ name="Vanya Hood", augments={'MP+50','"Fast Cast"+10','Haste+2%',}},
    body={ name="Adhemar Jacket", augments={'DEX+10','AGI+10','Accuracy+15',}},
    body={ name="Amalric Doublet", augments={'MP+60','Mag. Acc.+15','"Mag.Atk.Bns."+15',}},
    body={ name="Lustratio Harness", augments={'Accuracy+8','Attack+10','"Dbl.Atk."+3',}},
    body={ name="Souveran Cuirass", augments={'HP+80','Enmity+7','Potency of "Cure" effect received +10%',}},
    body={ name="Rawhide Vest", augments={'HP+50','"Subtle Blow"+7','"Triple Atk."+2',}},
    body={ name="Pursuer's Doublet", augments={'HP+50','Crit. hit rate+4%','"Snapshot"+6',}},
    body={ name="Vanya Robe", augments={'Healing magic skill +20','"Cure" spellcasting time -7%','Magic dmg. taken -3',}},
    hands={ name="Lustratio Mittens", augments={'Accuracy+15','DEX+5','Crit. hit rate+2%',}},
    hands={ name="Souv. Handschuhs", augments={'HP+50','Shield skill +10','Phys. dmg. taken -3',}},
    hands={ name="Argosy Mufflers", augments={'STR+15','"Dbl.Atk."+2','Haste+2%',}},
    hands={ name="Rao Kote", augments={'Accuracy+10','Attack+10','Evasion+15',}},
    hands={ name="Carmine Fin. Ga. +1", augments={'Rng.Atk.+20','"Mag.Atk.Bns."+12','"Store TP"+6',}},
    hands={ name="Rawhide Gloves", augments={'HP+50','Accuracy+15','Evasion+20',}},
    hands={ name="Pursuer's Cuffs", augments={'AGI+10','"Rapid Shot"+10','"Subtle Blow"+7',}},
    hands={ name="Vanya Cuffs", augments={'Healing magic skill +20','"Cure" spellcasting time -7%','Magic dmg. taken -3',}},
    hands={ name="Emicho Gauntlets", augments={'Pet: Accuracy+15','Pet: Attack+15','Pet: "Dbl. Atk."+3',}},
    hands={ name="Ryuo Tekko", augments={'DEX+10','Accuracy+20','"Dbl.Atk."+3',}},
    hands={ name="Adhemar Wristbands", augments={'AGI+10','Rng.Acc.+15','Rng.Atk.+15',}},
    hands={ name="Amalric Gages", augments={'INT+10','Mag. Acc.+15','"Mag.Atk.Bns."+15',}},
    legs={ name="Lustratio Subligar", augments={'Accuracy+15','DEX+5','Crit. hit rate+2%',}},
    legs={ name="Souveran Diechlings", augments={'HP+80','Enmity+7','Potency of "Cure" effect received +10%',}},
    legs={ name="Argosy Breeches", augments={'STR+10','Attack+20','"Store TP"+5',}},
    legs={ name="Rao Haidate", augments={'STR+10','DEX+10','Attack+15',}},
    legs={ name="Carmine Cuisses +1", augments={'Accuracy+20','Attack+12','"Dual Wield"+6',}},
    legs={ name="Rawhide Trousers", augments={'MP+50','"Fast Cast"+5','"Refresh"+1',}},
    legs={ name="Pursuer's Pants", augments={'AGI+10','"Rapid Shot"+10','"Subtle Blow"+7',}},
    legs={ name="Psycloth Lappas", augments={'MP+80','Mag. Acc.+15','"Fast Cast"+7',}},
    legs={ name="Vanya Slops", augments={'Healing magic skill +20','"Cure" spellcasting time -7%','Magic dmg. taken -3',}},
    legs={ name="Emicho Hose", augments={'Pet: Accuracy+15','Pet: Attack+15','Pet: "Dbl. Atk."+3',}},
    legs={ name="Ryuo Hakama", augments={'STR+10','DEX+10','Accuracy+15',}},
    legs={ name="Amalric Slops", augments={'MP+60','Mag. Acc.+15','"Mag.Atk.Bns."+15',}},
    feet={ name="Lustratio Leggings", augments={'Accuracy+15','DEX+5','Crit. hit rate+2%',}},
    feet={ name="Souveran Schuhs", augments={'HP+50','Attack+20','Magic dmg. taken -3',}},
    feet={ name="Argosy Sollerets", augments={'HP+50','"Dbl.Atk."+2','"Store TP"+3',}},
    feet={ name="Rao Sune-Ate", augments={'Accuracy+10','Attack+10','Evasion+15',}},
    feet={ name="Carmine Greaves +1", augments={'Accuracy+12','DEX+12','MND+20',}},
    feet={ name="Rawhide Boots", augments={'HP+50','Accuracy+15','Evasion+20',}},
    feet={ name="Pursuer's Gaiters", augments={'Rng.Acc.+10','"Rapid Shot"+10','"Recycle"+15',}},
    feet={ name="Vanya Clogs", augments={'Healing magic skill +20','"Cure" spellcasting time -7%','Magic dmg. taken -3',}},
    feet={ name="Emicho Gambieras", augments={'Pet: Accuracy+15','Pet: Attack+15','Pet: "Dbl. Atk."+3',}},
    feet={ name="Ryuo Sune-Ate", augments={'STR+10','DEX+10','Accuracy+15',}},
    feet={ name="Adhemar Gamashes", augments={'AGI+10','Rng.Acc.+15','Rng.Atk.+15',}},
    feet={ name="Amalric Nails", augments={'MP+60','Mag. Acc.+15','"Mag.Atk.Bns."+15',}},
    left_ear="Sabong Earring",
    left_ear="Zwazo Earring +1",
    left_ear="Lempo Earring",
    left_ear="Dedition Earring",
    left_ear="Thureous Earring",
    left_ear="Digni. Earring",
    left_ear="Odnowa Earring +1",
    left_ear="Mendi. Earring",
    left_ear="Infused Earring",
    left_ear="Enervating Earring",
    left_ear="Cryptic Earring",
    left_ear="Handler's Earring",
    left_ear="Handler's Earring +1",
    left_ear="Neritic Earring",
    left_ear="Zennaroi Earring",
    left_ear="Gwati Earring",
    left_ear="Friomisi Earring",
    left_ear="Tripudio Earring",
    left_ear="Steelflash Earring",
    left_ear="Bladeborn Earring",
    
    
    
    
     sub={ name="Sandung", augments={'Accuracy+50','Crit. hit rate+5%','"Triple Atk."+3',}},
    sub="Sequence",
    sub={ name="Kumbhakarna", augments={'Pet: Accuracy+19 Pet: Rng. Acc.+19','Pet: Phys. dmg. taken -2%','Pet: TP Bonus+180',}},
    sub={ name="Arktoi", augments={'Accuracy+50','Pet: Accuracy+50','Pet: Attack+30',}},
    sub="Izizoeksi",
    sub="Kerehcatl",
    sub="Charmer's Merlin",
    main="Dojikiri Yasutsuna",
    main={ name="Coeus", augments={'Mag. Acc.+41','"Mag.Atk.Bns."+8','"Fast Cast"+4',}},
    range={ name="Cibitshavore", augments={'STR+12','Rng.Acc.+10','"Store TP"+7',}},
    ammo="Vis. Broth",
    ammo="Windy Greens",
    ammo="Bubbly Broth",
    ammo="Tant. Broth",
    head={ name="Jumalik Helm", augments={'MND+10','"Mag.Atk.Bns."+15','Magic burst mdg.+10%','"Refresh"+1',}},
    head={ name="Dampening Tam", augments={'DEX+10','Accuracy+15','Mag. Acc.+15','Quadruple Attack +3',}},
    head={ name="Lilitu Headpiece", augments={'STR+10','DEX+10','Attack+15','Weapon skill damage +3%',}},
    head="Welkin Crown",
    head="Befouled Crown",
    head="Totemic Helm +1",
    head="Umuthi Hat",
    head={ name="Founder's Corona", augments={'DEX+10','Accuracy+15','Mag. Acc.+15','Magic dmg. taken -5%',}},
    head="Ferine Cabasset +1",
    body="Shango Robe",
    body="Vedic Coat",
    body="Nzingha Cuirass",
    body="Sayadio's Kaftan",
    body={ name="Luhlaza Jubbah +1", augments={'Enhances "Enchainment" effect',}},
    body={ name="Jumalik Mail", augments={'HP+50','Attack+13','Enmity+7','"Refresh"+1',}},
    body={ name="Samnuha Coat", augments={'Mag. Acc.+8','"Mag.Atk.Bns."+11','"Dual Wield"+2',}},
    body="Tot. Jackcoat +1",
    body="Mekosu. Harness",
    body={ name="Found. Breastplate", augments={'Accuracy+14','Mag. Acc.+13','Attack+14','"Mag.Atk.Bns."+14',}},
    hands={ name="Ankusa Gloves +1", augments={'Enhances "Beast Affinity" effect',}},
    hands="Nukumi Manoplas +1",
    hands={ name="Leyline Gloves", augments={'Accuracy+14','Mag. Acc.+13','"Mag.Atk.Bns."+13','"Fast Cast"+2',}},
    hands={ name="Floral Gauntlets", augments={'Rng.Acc.+15','Accuracy+15','"Triple Atk."+3','Magic dmg. taken -4%',}},
    hands="Macabre Gaunt. +1",
    hands={ name="Founder's Gauntlets", augments={'STR+10','Attack+15','"Mag.Atk.Bns."+15','Phys. dmg. taken -5%',}},
    legs="Arjuna Breeches",
    legs={ name="Ankusa Trousers +1", augments={'Enhances "Familiar" effect',}},
    legs={ name="Samnuha Tights", augments={'STR+10','DEX+10','"Dbl.Atk."+3','"Triple Atk."+3',}},
    legs={ name="Ta'lab Trousers", augments={'Accuracy+15','Mag. Evasion+15','Enmity-7','Crit.hit rate+3',}},
    legs="Assid. Pants +1",
    legs={ name="Founder's Hose", augments={'MND+9','Mag. Acc.+13','Attack+14','Breath dmg. taken -4%',}},
    legs={ name="Desultor Tassets", augments={'"Sic" and "Ready" ability delay -5','Pet: Accuracy+7 Pet: Rng. Acc.+7',}},
    feet={ name="Ankusa Gaiters +1", augments={'Enhances "Beast Healer" effect',}},
    feet={ name="Luhlaza Charuqs +1", augments={'Enhances "Diffusion" effect',}},
    feet="Inspirited Boots",
    feet={ name="Amm Greaves", augments={'HP+50','VIT+10','Accuracy+15','Damage taken-2%',}},
    feet={ name="Medium's Sabots", augments={'MP+40','MND+6','"Conserve MP"+5','"Cure" potency +3%',}},
    feet="Thereoid Greaves",
    feet="Jute Boots +1",
    feet={ name="Founder's Greaves", augments={'VIT+10','Accuracy+15','"Mag.Atk.Bns."+15','Mag. Evasion+15',}},
    feet="Ferine Ocreae +1",
    feet="Crier's Gaiters",
    waist="Ioskeha Belt",
    back="Perimede Cape",
    back="Solemnity Cape",
    back="Argocham. Mantle",
    back="Ground. Mantle +1",
    back="Xucau Mantle",
    back="Vespid Mantle",
    back="Estoqueur's Cape",
    left_ring="Dim. Ring (Dem)",
    left_ring="Ifrit Ring",
    left_ring="Ifrit Ring",
    left_ring="Thurandaut Ring",
    left_ring="Globidonta Ring",
    left_ring="Locus Ring",
    left_ring="Tjukurrpa Annulet",
    left_ring="Paguroidea Ring",
    left_ring="Archon Ring",
    left_ring="Epona's Ring",
    left_ring="Mujin Band",
    left_ring="Excelsis Ring",
    left_ring="Antica Ring",
    left_ring="Defending Ring",
    left_ring="Rajas Ring",
    left_ring="Warp Ring",
    
    
    
       ammo="Happo Shuriken",
    ammo="Ginsen",
    ammo="Seraphic Ampulla",
    ammo="Falcon Eye",
    ammo="Amar Cluster",
    ammo="Mantoptera Eye",
    ammo="Elis Tome",
    ammo="Pemphredo Tathlum",
    ammo="Demonry Core",
    ammo="Mavi Tathlum",
    range="Aureole",
    sub="Bloodrain Strap",
    sub="Mephitis Grip",
    sub="Niobid Strap",
    sub="Gracile Grip",
    sub="Pole Grip",
    sub="Culminus",
    sub="Chanter's Shield",
    sub={ name="Beatific Shield", augments={'Phys. dmg. taken -3%','HP+30 MP+30',}},
    neck="Orunmila's Torque",
    neck="Lissome Necklace",
    neck="Carnal Torque",
    neck="Decimus Torque",
    neck="Bilious Torque",
    neck="Yarak Torque",
    neck="Maskirova Torque",
    neck="Clotharius Torque",
    neck="Deino Collar",
    neck="Ainia Collar",
    neck="Sanctity Necklace",
    neck="Marked Gorget",
    neck="Empath Necklace",
    neck="Diemer Gorget",
    neck="Nodens Gorget",
    neck="Mizu. Kubikazari",
    neck="Twilight Torque",
    neck="Magoraga Beads",
    neck="Fotia Gorget",
    waist="Caudata Belt",
    waist="Reiki Yotai",
    waist="Refoccilation Stone",
    waist="Channeler's Stone",
    waist="Asklepian Belt",
    waist="Sarissapho. Belt",
    waist="Luminary Sash",
    waist="Kwahu Kachina Belt",
    waist="Kentarch Belt +1",
    waist="Eschan Stone",
    waist="Incarnation Sash",
    waist="Chiner's Belt +1",
    waist="Windbuffet Belt +1",
    waist="Ponente Sash",
    waist="Olseni Belt",
    waist="Chaac Belt",
    waist="Isa Belt",
    waist="Dynamic Belt +1",
    waist="Siegel Sash",
    waist="Fotia Belt",
    waist="Hyorin Obi",
    waist="Rairin Obi",
    waist="Anrin Obi",
    back={ name="Taranus's Cape", augments={'INT+20','Mag. Acc+20 /Mag. Dmg.+20','"Mag.Atk.Bns."+10',}},
    back={ name="Artio's Mantle", augments={'Pet: Acc.+20 Pet: R.Acc.+20 Pet: Atk.+20 Pet: R.Atk.+20','Accuracy+20 Attack+20','Pet: "Regen"+10',}},
    back={ name="Smertrios's Mantle", augments={'STR+20','Accuracy+20 Attack+20','STR+10','Weapon skill damage +10%',}},
    back={ name="Smertrios's Mantle", augments={'DEX+20','Accuracy+20 Attack+20','Accuracy+10','"Store TP"+10',}},
    back={ name="Andartia's Mantle", augments={'AGI+20','Accuracy+20 Attack+20','Weapon skill damage +10%',}},
    back={ name="Andartia's Mantle", augments={'DEX+20','Accuracy+20 Attack+20','Accuracy+10','"Dbl.Atk."+10',}},
    back={ name="Rosmerta's Cape", augments={'DEX+20','Accuracy+20 Attack+20','DEX+10','Crit.hit rate+10',}},
    back={ name="Rosmerta's Cape", augments={'STR+20','Accuracy+20 Attack+20','Weapon skill damage +10%',}},
    back={ name="Anchoret's Mantle", augments={'STR+4','DEX+3','"Subtle Blow"+3','"Counter"+2',}},
    back={ name="Bane Cape", augments={'Elem. magic skill +9','Dark magic skill +5','"Mag.Atk.Bns."+2','"Fast Cast"+4',}},
    back={ name="Ghostfyre Cape", augments={'Enfb.mag. skill +7','Enha.mag. skill +1','Mag. Acc.+8',}},
    back={ name="Canny Cape", augments={'DEX+4','AGI+1','"Dual Wield"+4','Crit. hit damage +1%',}},
    back={ name="Pastoralist's Mantle", augments={'STR+1 DEX+1','Pet: Accuracy+14 Pet: Rng. Acc.+14','Pet: Damage taken -5%',}},
    back={ name="Takaha Mantle", augments={'STR+4','"Zanshin"+3','"Store TP"+2','Meditate eff. dur. +5',}},
    back={ name="Yokaze Mantle", augments={'STR+2','DEX+3','Sklchn.dmg.+4%',}},
    back={ name="Cornflower Cape", augments={'MP+30','DEX+2','Accuracy+2','Blue Magic skill +9',}},
    back={ name="Bookworm's Cape", augments={'INT+1','MND+4','Helix eff. dur. +11','"Regen" potency+7',}},
    back={ name="Evasionist's Cape", augments={'Enmity+1','"Embolden"+7','"Dbl.Atk."+1',}},
    left_ring="Lebeche Ring",
    
    
       sub="Kustawi +1",
    sub="Fettering Blade",
    range={ name="Compensator", augments={'DMG:+15','Rng.Acc.+15','Rng.Atk.+15',}},
    range="Fomalhaut",
    ammo="Chrono Bullet",
    ammo="Chrono Bullet",
    sub="Nusku Shield",
    head="Mummu Bonnet +1",
    head="Meghanada Visor +1",
    head={ name="Arcadian Beret +1", augments={'Enhances "Recycle" effect',}},
    head={ name="Lanun Tricorne +1", augments={'Enhances "Winning Streak" effect',}},
    head="Amini Gapette +1",
    head="Orion Beret +1",
    head="Lak. Hat +1",
    body="Laksa. Frac +2",
    body="Meg. Cuirie +1",
    body="Mummu Jacket +1",
    body={ name="Arc. Jerkin +1", augments={'Enhances "Snapshot" effect',}},
    body={ name="Lanun Frac +1", augments={'Enhances "Loaded Deck" effect',}},
    body="Amini Caban +1",
    hands="Meg. Gloves +1",
    hands="Mummu Wrists +1",
    hands={ name="Arc. Bracers +1", augments={'Enhances "Flashy Shot" effect',}},
    hands={ name="Lanun Gants +1", augments={'Enhances "Fold" effect',}},
    hands="Chasseur's Gants +1",
    hands="Orion Bracers +1",
    legs="Meg. Chausses +1",
    legs="Mummu Kecks +1",
    legs={ name="Arc. Braccae +1", augments={'Enhances "Eagle Eye Shot" effect',}},
    feet="Mummu Gamash. +1",
    waist="Impulse Belt",
    left_ring="Luzaf's Ring",
    item="Mythril Sheet",
    item="Rosewood Lbr.",
    item="Undead Skin",
    item="Gold Thread",
    item="Mythril Ingot",
    item="Coeurl Leather",
    left_ring="Barataria Ring",
    item="Iron Sheet",
    feet="Wicce Sabots +1",
    feet="Jhakri Pigaches +1",
    legs="Jhakri Slops +1",
    hands="Jhakri Cuffs +1",
    head="Jhakri Coronal +1",
    item="Abdhaljs Sap",
    item="Abdhaljs Dye",
    item="Abdhaljs Dust",
    item="Abdhaljs Thread",
    item="Warblade's Hide",
    item="Cerberus Hide",
    item="Manticore Hide",
    item="Beeswax",
    item="Beeswax",
    item="Beeswax",
    item="Behem. Leather",
    item="Behemoth Hide",
    item="Behemoth Hide",
    item="Tiger Leather",
    item="Ram Leather",
    item="Sheep Leather",
    item="Undead Skin",
    left_ring="Dingir Ring",
    back={ name="Camulus's Mantle", augments={'"Snapshot"+10',}},
    back={ name="Camulus's Mantle", augments={'AGI+20','Rng.Acc.+20 Rng.Atk.+20','Rng.Acc.+10','"Store TP"+10',}},
    back={ name="Camulus's Mantle", augments={'AGI+20','Mag. Acc+20 /Mag. Dmg.+20','AGI+10','"Mag.Atk.Bns."+10',}},
    neck="Ocachi Gorget",
    feet="Lak. Bottes +1",
    feet="Hattori Kyahan +1",
    feet={ name="Lanun Bottes +1", augments={'Enhances "Wild Card" effect',}},
    feet={ name="Arcadian Socks +1", augments={'Enhances "Stealth Shot" effect',}},
    feet="Meg. Jam. +1",
    legs="Lak. Trews +1",
    legs="Orion Braccae +1",
    legs={ name="Lanun Culottes +1", augments={'Enhances "Snake Eye" effect',}},
    
    
     main="Denouements",
    sub={ name="Malevolence", augments={'INT+3','Mag. Acc.+5','"Mag.Atk.Bns."+7',}},
    sub={ name="Malevolence", augments={'INT+9','Mag. Acc.+10','"Mag.Atk.Bns."+9','"Fast Cast"+4',}},
    sub={ name="Taming Sari", augments={'STR+9','DEX+8','DMG:+14',}},
    sub="Oneiros Knife",
    sub={ name="Brilliance", augments={'Shield skill +8','Divine magic skill +13','Enmity+5','DMG:+14',}},
    sub={ name="Vampirism", augments={'STR+6','INT+5','"Occult Acumen"+5','DMG:+7',}},
    sub={ name="Vampirism", augments={'STR+6','INT+5','"Occult Acumen"+5','DMG:+7',}},
    sub="Demers. Degen +1",
    sub="Excalipoor II",
    sub="Excalipoor II",
    main={ name="Bidenhander", augments={'DMG:+30','Accuracy+20','Attack+20',}},
    sub="Perun",
    sub="Perun +1",
    sub={ name="Kumbhakarna", augments={'Pet: Attack+14 Pet: Rng.Atk.+14','Pet: Phys. dmg. taken -4%','Pet: STR+13 Pet: DEX+13 Pet: VIT+13',}},
    sub={ name="Ochu", augments={'STR+7','DEX+8','Ninjutsu skill +7','DMG:+8',}},
    sub={ name="Kanaria", augments={'"Triple Atk."+2','DEX+1','Accuracy+16','Attack+17','DMG:+18',}},
    sub={ name="Rubicundity", augments={'Mag. Acc.+10','"Mag.Atk.Bns."+10','Dark magic skill +10','"Conserve MP"+7',}},
    main={ name="Akademos", augments={'INT+15','"Mag.Atk.Bns."+15','Mag. Acc.+15',}},
    main={ name="Lathi", augments={'INT+15','"Mag.Atk.Bns."+15','Mag. Acc.+15',}},
    main="Contemplator",
    range={ name="Nobility", augments={'AGI+10','Crit.hit rate+4','"Store TP"+8','DMG:+15',}},
    range={ name="Teller", augments={'Weapon skill damage +2%','Rng.Acc.+23','Rng.Atk.+19','DMG:+15',}},
    range="Steinthor",
    range="Wolver Bow",
    range="Wochowsen",
    ammo="Eminent Arrow",
    ammo="Achiyal. Arrow",
    ammo="Achiyal. Bolt",
    sub="Enki Strap",
    head="Ynglinga Sallet",
    head={ name="Souveran Schaller", augments={'Accuracy+10','Attack+10','Enmity+4',}},
    head="Skulker's Bonnet +1",
    head="Skormoth Mask",
    head="Frenzy Sallet",
    body={ name="Odyss. Chestplate", augments={'Accuracy+30','Weapon Skill Acc.+15','INT+6','Attack+1',}},
    body={ name="Herculean Vest", augments={'Mag. Acc.+20 "Mag.Atk.Bns."+20','STR+10','Mag. Acc.+15','"Mag.Atk.Bns."+12',}},
    body="Jhakri Robe +1",
    body="Flamma Korazin +1",
    body={ name="Samnuha Coat", augments={'Mag. Acc.+12','"Fast Cast"+3','"Dual Wield"+2',}},
    hands="Mrigavyadha Gloves",
    hands={ name="Plun. Armlets +1", augments={'Enhances "Perfect Dodge" effect',}},
    hands="Skulk. Armlets +1",
    hands="Kobo Kote",
    legs={ name="Valor. Hose", augments={'MND+8','Accuracy+7 Attack+7','Phalanx +2','Mag. Acc.+11 "Mag.Atk.Bns."+11',}},
    legs={ name="Adhemar Kecks", augments={'AGI+10','"Rapid Shot"+10','Enmity-5',}},
    feet={ name="Carmine Greaves", augments={'Accuracy+10','DEX+10','MND+15',}},
    feet={ name="Valorous Greaves", augments={'"Cure" potency +4%','MND+2','"Refresh"+2','Accuracy+5 Attack+5',}},
    neck="Loricate Torque +1",
    neck="Anu Torque",
    waist="Flume Belt +1",
    back={ name="Cichol's Mantle", augments={'DEX+20','Accuracy+20 Attack+20','"Dbl.Atk."+10',}},
    back={ name="Segomo's Mantle", augments={'DEX+20','Accuracy+20 Attack+20','"Dbl.Atk."+10',}},
    back={ name="Taranus's Cape", augments={'MP+60','Mag. Acc+20 /Mag. Dmg.+20','MP+20','"Mag.Atk.Bns."+10',}},
    back={ name="Toutatis's Cape", augments={'DEX+20','Accuracy+20 Attack+20','Crit.hit rate+10',}},
    back={ name="Rudianos's Mantle", augments={'VIT+20','Accuracy+20 Attack+20','"Dbl.Atk."+10',}},
    back={ name="Belenus's Cape", augments={'"Snapshot"+10',}},
    back={ name="Belenus's Cape", augments={'AGI+20','Rng.Acc.+20 Rng.Atk.+20','AGI+10','Weapon skill damage +10%',}},
    back={ name="Belenus's Cape", augments={'AGI+20','Rng.Acc.+20 Rng.Atk.+20','Rng.Acc.+10','"Store TP"+10',}},
    back={ name="Brigantia's Mantle", augments={'DEX+20','Accuracy+20 Attack+20','"Dbl.Atk."+10',}},
    back={ name="Senuna's Mantle", augments={'DEX+20','Accuracy+20 Attack+20','"Store TP"+10',}},
    back={ name="Lugh's Cape", augments={'INT+20','Mag. Acc+20 /Mag. Dmg.+20','"Mag.Atk.Bns."+10',}},
    back={ name="Ogma's cape", augments={'DEX+20','Accuracy+20 Attack+20','Accuracy+10','"Store TP"+10',}},
    left_ear="Sherida Earring",
    left_ear="Cessance Earring",
    left_ear="Hermetic Earring",
    left_ear="Hecate's Earring",
    left_ear="Reraise Earring",
    left_ring="Hetairoi Ring",
    left_ring="Ilabrat Ring",
    left_ring="Kishar Ring",
    left_ring="Patricius Ring",
    
    
    
    
     main="Inferno Claws",
    sub="Swordbreaker",
    sub="Dancing Dagger",
    sub="Main Gauche",
    sub="Wightslayer",
    main="Sturdy Axe",
    main="Radiant Lance",
    sub="Sasuke Katana",
    main="Windslicer",
    main="Mage's Staff",
    main="Elder Staff",
    head={ name="Acro Helm", augments={'Accuracy+10','Haste+3','STR+1 VIT+1',}},
    head={ name="Taeon Chapeau", augments={'Accuracy+14 Attack+14','"Triple Atk."+2',}},
    head={ name="Naga Somen", augments={'STR+7','Accuracy+9','"Subtle Blow"+5',}},
    body={ name="Witching Robe", augments={'MP+10','Mag. Acc.+5',}},
    body={ name="Taeon Tabard", augments={'Pet: Accuracy+24 Pet: Rng. Acc.+24','Pet: "Dbl. Atk."+3','Pet: Haste+5',}},
    body={ name="Despair Mail", augments={'Accuracy+10','Pet: VIT+7','Pet: Damage taken -3%',}},
    body={ name="Naga Samue", augments={'STR+9','Accuracy+13','"Subtle Blow"+6',}},
    body={ name="Psycloth Vest", augments={'Elem. magic skill +20','INT+7','Enmity-6',}},
    hands={ name="Carmine Fin. Ga.", augments={'Rng.Atk.+15','"Mag.Atk.Bns."+10','"Store TP"+5',}},
    hands={ name="Taeon Gloves", augments={'Pet: Accuracy+10 Pet: Rng. Acc.+10','Pet: "Dbl. Atk."+2',}},
    hands={ name="Despair Fin. Gaunt.", augments={'Accuracy+10','Pet: VIT+7','Pet: Damage taken -3%',}},
    hands={ name="Naga Tekko", augments={'STR+10','Accuracy+15','"Subtle Blow"+7',}},
    hands={ name="Psycloth Manillas", augments={'MP+50','INT+7','"Conserve MP"+6',}},
    legs={ name="Taeon Tights", augments={'Accuracy+19 Attack+19','"Triple Atk."+1',}},
    legs={ name="Despair Cuisses", augments={'Accuracy+10','Pet: VIT+7','Pet: Damage taken -3%',}},
    legs={ name="Naga Hakama", augments={'STR+10','Accuracy+15','"Subtle Blow"+7',}},
    legs={ name="Enticer's Pants", augments={'MP+50','Pet: Accuracy+13 Pet: Rng. Acc.+13','Pet: Mag. Acc.+14','Pet: Damage taken -4%',}},
    feet={ name="Taeon Boots", augments={'Pet: Accuracy+18 Pet: Rng. Acc.+18','Pet: "Dbl. Atk."+3','CHR+9',}},
    feet={ name="Despair Greaves", augments={'Accuracy+10','Pet: VIT+7','Pet: Damage taken -3%',}},
    feet={ name="Naga Kyahan", augments={'STR+10','Accuracy+15','"Subtle Blow"+7',}},
    feet={ name="Psycloth Boots", augments={'MP+50','INT+7','"Conserve MP"+6',}},
    left_ear="Lugra Earring",
