    sub={ name="Skinflayer", augments={'"Triple Atk."+2','CHR+1','Accuracy+19','Attack+19','DMG:+18',}},
    sub={ name="Skinflayer", augments={'"Triple Atk."+3','Accuracy+10','Attack+13','DMG:+17',}},
    sub={ name="Colada", augments={'"Refresh"+2','INT+1','Mag. Acc.+15','"Mag.Atk.Bns."+10',}},
    sub={ name="Colada", augments={'"Store TP"+5','VIT+2','Accuracy+25',}},
    main={ name="Zulfiqar", augments={'Weapon Skill Acc.+5','STR+6','Attack+14','DMG:+24',}},
    sub={ name="Kumbhakarna", augments={'Pet: Accuracy+19 Pet: Rng. Acc.+19','Pet: Phys. dmg. taken -2%','Pet: TP Bonus+180',}},
    sub={ name="Kanaria", augments={'"Triple Atk."+3','DEX+6','Accuracy+20','Attack+8','DMG:+3',}},
    main={ name="Grioavolr", augments={'"Fast Cast"+7','MP+54','Mag. Acc.+29','"Mag.Atk.Bns."+28','Magic Damage +3',}},
    head={ name="Odyssean Helm", augments={'Accuracy+28','"Dbl.Atk."+3','CHR+4','"Mag.Atk.Bns."+3',}},
    head={ name="Odyssean Helm", augments={'Attack+9','Weapon skill damage +4%','STR+3','Accuracy+13',}},
    head={ name="Valorous Mask", augments={'Accuracy+30','"Dbl.Atk."+2','STR+2','Attack+12',}},
    head={ name="Valorous Mask", augments={'Pet: Accuracy+30 Pet: Rng. Acc.+30','"Store TP"+1','Pet: DEX+10','Pet: Attack+14 Pet: Rng.Atk.+14',}},
    head={ name="Valorous Mask", augments={'Accuracy+28','Weapon skill damage +3%','STR+15','Attack+12',}},
    head={ name="Herculean Helm", augments={'Mag. Acc.+19 "Mag.Atk.Bns."+19','Crit. hit damage +2%','STR+9','"Mag.Atk.Bns."+12',}},
    head={ name="Herculean Helm", augments={'Rng.Acc.+28','"Subtle Blow"+1','DEX+1','Rng.Atk.+15',}},
    head={ name="Merlinic Hood", augments={'Mag. Acc.+17 "Mag.Atk.Bns."+17','"Fast Cast"+6','INT+6','Mag. Acc.+10','"Mag.Atk.Bns."+14',}},
    head={ name="Merlinic Hood", augments={'Mag. Acc.+23 "Mag.Atk.Bns."+23','Magic burst mdg.+4%','Mag. Acc.+13','"Mag.Atk.Bns."+9',}},
    head={ name="Chironic Hat", augments={'Mag. Acc.+25 "Mag.Atk.Bns."+25','"Conserve MP"+1','VIT+1','Mag. Acc.+8',}},
    head="Chironic Hat",
    body={ name="Valorous Mail", augments={'Pet: Accuracy+30 Pet: Rng. Acc.+30','Pet: "Store TP"+3','Pet: DEX+14',}},
    body={ name="Valorous Mail", augments={'Accuracy+28','Sklchn.dmg.+4%','STR+9','Attack+15',}},
    body={ name="Herculean Vest", augments={'Accuracy+28','Crit.hit rate+5','DEX+5','Attack+12',}},
    body={ name="Merlinic Jubbah", augments={'Mag. Acc.+24 "Mag.Atk.Bns."+24','Magic burst mdg.+10%','CHR+7',}},
    body={ name="Chironic Doublet", augments={'Mag. Acc.+29','Enmity-4','MND+2','"Mag.Atk.Bns."+6',}},
    body={ name="Chironic Doublet", augments={'Mag. Acc.+12','"Cure" potency +11%',}},
    body={ name="Acro Surcoat", augments={'Pet: Accuracy+10 Pet: Rng. Acc.+10','Pet: "Regen"+3','Pet: Damage taken -4%',}},
    hands={ name="Acro Gauntlets", augments={'Pet: Accuracy+17 Pet: Rng. Acc.+17','Pet: "Regen"+3','Pet: Damage taken -4%',}},
    hands={ name="Odyssean Gauntlets", augments={'Accuracy+22','DEX+9','Attack+3',}},
    hands={ name="Odyssean Gauntlets", augments={'Mag. Acc.+24','Weapon skill damage +3%','MND+9',}},
    hands={ name="Valorous Mitts", augments={'Pet: Accuracy+28 Pet: Rng. Acc.+28','Pet: "Regen"+1','Pet: DEX+4','Pet: Attack+11 Pet: Rng.Atk.+11',}},
    hands={ name="Valorous Mitts", augments={'Accuracy+16 Attack+16','"Store TP"+4','VIT+8','Accuracy+14',}},
    hands={ name="Valorous Mitts", augments={'Accuracy+19 Attack+19','Magic dmg. taken -2%','VIT+10','Accuracy+15','Attack+15',}},
    hands={ name="Valorous Mitts", augments={'Accuracy+27','"Dbl.Atk."+2','STR+15',}},
    hands={ name="Herculean Gloves", augments={'Accuracy+16','Crit.hit rate+5','DEX+1',}},
    hands={ name="Herculean Gloves", augments={'Rng.Acc.+18 Rng.Atk.+18','Enmity-3','AGI+6','Rng.Acc.+9','Rng.Atk.+1',}},
    hands={ name="Herculean Gloves", augments={'Accuracy+29','"Triple Atk."+3','STR+9',}},
    hands={ name="Merlinic Dastanas", augments={'Mag. Acc.+21 "Mag.Atk.Bns."+21','INT+8','Mag. Acc.+3','"Mag.Atk.Bns."+15',}},
    hands={ name="Chironic Gloves", augments={'Mag. Acc.+24 "Mag.Atk.Bns."+24','MND+6','Mag. Acc.+10','"Mag.Atk.Bns."+14',}},
    hands="Chironic Gloves",
    legs={ name="Odyssean Cuisses", augments={'Accuracy+21','STR+14',}},
    legs={ name="Valor. Hose", augments={'Pet: Accuracy+30 Pet: Rng. Acc.+30','Pet: Haste+2','Pet: INT+10','Pet: Attack+14 Pet: Rng.Atk.+14',}},
    legs={ name="Valor. Hose", augments={'Accuracy+24 Attack+24','"Store TP"+5','VIT+8','Accuracy+3',}},
    legs={ name="Herculean Trousers", augments={'Pet: Phys. dmg. taken -1%','"Fast Cast"+3','"Treasure Hunter"+1','Accuracy+11 Attack+11','Mag. Acc.+1 "Mag.Atk.Bns."+1',}},
    legs={ name="Herculean Trousers", augments={'Accuracy+14 Attack+14','DEX+9','Accuracy+15','Attack+14',}},
    legs={ name="Herculean Trousers", augments={'Attack+27','"Triple Atk."+4','AGI+4','Accuracy+15',}},
    legs={ name="Herculean Trousers", augments={'Rng.Acc.+23 Rng.Atk.+23','Enmity-1','AGI+7','Rng.Atk.+15',}},
    legs={ name="Merlinic Shalwar", augments={'"Mag.Atk.Bns."+21','Magic burst mdg.+9%','INT+1','Mag. Acc.+13',}},
    legs={ name="Merlinic Shalwar", augments={'Mag. Acc.+24 "Mag.Atk.Bns."+24','"Occult Acumen"+9','CHR+5','"Mag.Atk.Bns."+13',}},
    legs="Chironic Hose",
    legs={ name="Chironic Hose", augments={'Mag. Acc.+24 "Mag.Atk.Bns."+24','"Cure" spellcasting time -8%','Mag. Acc.+14',}},
    legs={ name="Taeon Tights", augments={'Pet: Accuracy+5 Pet: Rng. Acc.+5','Pet: "Regen"+3','Pet: Damage taken -4%',}},
    feet={ name="Acro Leggings", augments={'Pet: Attack+19 Pet: Rng.Atk.+19','Pet: "Regen"+3','Pet: Damage taken -4%',}},
    feet={ name="Odyssean Greaves", augments={'Accuracy+23','"Dbl.Atk."+2','STR+3',}},
    feet={ name="Odyssean Greaves", augments={'"Fast Cast"+3','VIT+5','Accuracy+9','Attack+15',}},
    feet={ name="Odyssean Greaves", augments={'Mag. Acc.+14 "Mag.Atk.Bns."+14','"Store TP"+5','MND+1','"Mag.Atk.Bns."+15',}},
    feet={ name="Valorous Greaves", augments={'Accuracy+24 Attack+24','Damage taken-1%','Accuracy+14',}},
    feet={ name="Valorous Greaves", augments={'Pet: Accuracy+28 Pet: Rng. Acc.+28','Pet: "Dbl. Atk."+1','Pet: DEX+9','Pet: Attack+5 Pet: Rng.Atk.+5',}},
    feet={ name="Valorous Greaves", augments={'Accuracy+27','"Store TP"+5','DEX+9','Attack+10',}},
    feet={ name="Herculean Boots", augments={'Accuracy+14 Attack+14','"Triple Atk."+4','VIT+6','Accuracy+5',}},
    feet={ name="Herculean Boots", augments={'Rng.Acc.+20 Rng.Atk.+20','Crit.hit rate+2','Rng.Acc.+12','Rng.Atk.+9',}},
    feet={ name="Herculean Boots", augments={'AGI+10','"Store TP"+2','Magic Damage +17','Mag. Acc.+20 "Mag.Atk.Bns."+20',}},
    feet={ name="Merlinic Crackows", augments={'INT+1','Phys. dmg. taken -4%','"Refresh"+1','Accuracy+8 Attack+8',}},
    feet={ name="Merlinic Crackows", augments={'Mag. Acc.+24 "Mag.Atk.Bns."+24','Magic burst mdg.+7%','CHR+2','Mag. Acc.+6','"Mag.Atk.Bns."+14',}},
    feet={ name="Chironic Slippers", augments={'Mag. Acc.+23 "Mag.Atk.Bns."+23','Haste+4','Mag. Acc.+13',}},
    feet="Chironic Slippers",
    back={ name="Rosmerta's Cape", augments={'DEX+20','Accuracy+20 Attack+20','Crit.hit rate+10',}},
    back={ name="Evasionist's Cape", augments={'Enmity+1','"Embolden"+7','"Dbl.Atk."+1',}},
    back={ name="Bookworm's Cape", augments={'INT+1','MND+4','Helix eff. dur. +11','"Regen" potency+7',}},
    back={ name="Cornflower Cape", augments={'MP+30','DEX+2','Accuracy+2','Blue Magic skill +9',}},
    back={ name="Yokaze Mantle", augments={'STR+2','DEX+3','Sklchn.dmg.+4%',}},
    back={ name="Takaha Mantle", augments={'STR+4','"Zanshin"+3','"Store TP"+2','Meditate eff. dur. +5',}},
    back={ name="Lutian Cape", augments={'STR+3','AGI+5','"Store TP"+1','"Snapshot"+3',}},
    back={ name="Pastoralist's Mantle", augments={'STR+1 DEX+1','Pet: Accuracy+14 Pet: Rng. Acc.+14','Pet: Damage taken -5%',}},
    back={ name="Canny Cape", augments={'DEX+4','AGI+1','"Dual Wield"+4','Crit. hit damage +1%',}},
    back={ name="Ghostfyre Cape", augments={'Enfb.mag. skill +7','Enha.mag. skill +1','Mag. Acc.+8',}},
    back={ name="Bane Cape", augments={'Elem. magic skill +9','Dark magic skill +5','"Mag.Atk.Bns."+2','"Fast Cast"+4',}},
    back={ name="Anchoret's Mantle", augments={'STR+4','DEX+3','"Subtle Blow"+3','"Counter"+2',}},
    back={ name="Rosmerta's Cape", augments={'STR+20','Accuracy+20 Attack+20','Weapon skill damage +10%',}},
    back={ name="Andartia's Mantle", augments={'AGI+20','Accuracy+20 Attack+20','Weapon skill damage +10%',}},
    back={ name="Andartia's Mantle", augments={'DEX+20','Accuracy+20 Attack+20','"Dbl.Atk."+10',}},
    back={ name="Smertrios's Mantle", augments={'DEX+20','Accuracy+20 Attack+20','"Store TP"+10',}},
    back={ name="Smertrios's Mantle", augments={'STR+20','Accuracy+20 Attack+20','Weapon skill damage +10%',}},
    back={ name="Artio's Mantle", augments={'Pet: Acc.+20 Pet: R.Acc.+20 Pet: Atk.+20 Pet: R.Atk.+20','Accuracy+20 Attack+20','Pet: "Regen"+10',}},
    back={ name="Taranus's Cape", augments={'INT+20','Mag. Acc+20 /Mag. Dmg.+20','"Mag.Atk.Bns."+10',}},
    head={ name="Acro Helm", augments={'Accuracy+10','Haste+3','STR+1 VIT+1',}},
    head={ name="Taeon Chapeau", augments={'Accuracy+14 Attack+14','"Triple Atk."+2',}},
    body={ name="Taeon Tabard", augments={'Pet: Accuracy+24 Pet: Rng. Acc.+24','Pet: "Dbl. Atk."+3','Pet: Haste+5',}},
    hands={ name="Taeon Gloves", augments={'Pet: Accuracy+10 Pet: Rng. Acc.+10','Pet: "Dbl. Atk."+2',}},
    legs={ name="Taeon Tights", augments={'Accuracy+19 Attack+19','"Triple Atk."+1',}},
    feet={ name="Taeon Boots", augments={'Pet: Accuracy+18 Pet: Rng. Acc.+18','Pet: "Dbl. Atk."+3','CHR+9',}},
	  sub={ name="Malevolence", augments={'INT+9','Mag. Acc.+10','"Mag.Atk.Bns."+9','"Fast Cast"+4',}},
    sub={ name="Malevolence", augments={'INT+3','Mag. Acc.+5','"Mag.Atk.Bns."+7',}},
    sub={ name="Taming Sari", augments={'STR+9','DEX+8','DMG:+14',}},
    sub={ name="Emissary", augments={'Mag. Acc.+15','"Mag.Atk.Bns."+20','"Refresh"+1',}},
    sub={ name="Vampirism", augments={'STR+3','INT+5','"Occult Acumen"+3','DMG:+3',}},
    sub={ name="Vampirism", augments={'STR+6','INT+5','"Occult Acumen"+5','DMG:+7',}},
    sub={ name="Kumbhakarna", augments={'Pet: Attack+14 Pet: Rng.Atk.+14','Pet: Phys. dmg. taken -4%','Pet: STR+13 Pet: DEX+13 Pet: VIT+13',}},
    sub={ name="Rubicundity", augments={'Mag. Acc.+10','"Mag.Atk.Bns."+10','Dark magic skill +10','"Conserve MP"+7',}},
    range={ name="Nobility", augments={'AGI+10','Crit.hit rate+4','"Store TP"+8','DMG:+15',}},
    range={ name="Teller", augments={'Weapon skill damage +2%','Rng.Acc.+23','Rng.Atk.+19','DMG:+15',}},
    main={ name="Bidenhander", augments={'DMG:+30','Accuracy+20','Attack+20',}},
    sub={ name="Skullrender", augments={'DMG:+15','Pet: Accuracy+20','Pet: Attack+20',}},
    sub={ name="Skullrender", augments={'DMG:+15','Pet: Accuracy+20','Pet: Attack+20',}},
    sub={ name="Nibiru Tabar", augments={'Pet: Attack+25','Pet: "Mag.Atk.Bns."+15','Pet: Enmity+7',}},
    sub={ name="Nibiru Tabar", augments={'Pet: Attack+25','Pet: "Mag.Atk.Bns."+15','Pet: Enmity+7',}},
    sub={ name="Nibiru Cudgel", augments={'MP+50','INT+10','"Mag.Atk.Bns."+15',}},
    main={ name="Akademos", augments={'INT+15','"Mag.Atk.Bns."+15','Mag. Acc.+15',}},    
